import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-providers";
import ConvexClientProvider from "@/providers/convex-client-provider";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import {Toaster} from "react-hot-toast"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
        <ConvexClientProvider>
        <SignedOut>
          <SignInButton />
        </SignedOut>
        {/* <SignedIn>
          <UserButton />
        </SignedIn> */}
          {children}
          <Toaster />
        </ConvexClientProvider>
</ThemeProvider>
</body>
    </html>
    // </ClerkProvider>
  );
}
